NetCoreMVC/NetCoreMVC/Entities/City.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreMVC.Entities
{
    public class City
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
        [MaxLength(200)]
        public string Description { get; set; }
        public ICollection<PointOfInterest> PointsOfInterest { get; set; } = new List<PointOfInterest>();
    }
}

NetCoreMVC/NetCoreMVC/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NetCoreMVC.Entities;
using NetCoreMVC.Models;
using Serilog;

namespace NetCoreMVC.Controllers
{
    public class CitiesController : Controller
    {
        private readonly CityInfoContext _context;

        public CitiesController(CityInfoContext context)
        {
            _context = context;
        }

        // GET: Cities
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "My Cities";
            var cityEntities = await _context.Cities.ToListAsync();
            return View(Mapper.Map<IEnumerable<CityDto>>(cityEntities));
        }

        // GET: Cities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                Log.Information("(Details) City was not found");
                return NotFound();
            }

            var cityEntity = await _context.Cities
                .SingleOrDefaultAsync(m => m.Id == id);
            var city = Mapper.Map<CityDetailsDto>(cityEntity);
            if (city == null)
            {
                Log.Information("(Details) City was not found");
                return NotFound();
            }

            ViewBag.Title = $@"{city.Name} Details";

            return View(city);
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
            ViewBag.Title = "Create City";
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create(CityCreationDto city)
        {
            if (ModelState.IsValid)
            {
                var finalCity = Mapper.Map<City>(city);
                _context.Add(finalCity);
                await _context.SaveChangesAsync();
                Log.Information("(Create) City created " + city.Name);
                return RedirectToAction(nameof(Index));
            }
            return View(city);
        }

        // GET: Cities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                Log.Information("(Edit) City was not found");
                return NotFound();
            }

            var cityEntity = await _context.Cities.SingleOrDefaultAsync(m => m.Id == id);
            var city = Mapper.Map<CityEditDto>(cityEntity);
            if (city == null)
            {
                Log.Information("(Edit) City was not found");
                return NotFound();
            }
            ViewBag.Title = $@"Edit {city.Name}";

            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Edit(int id, CityEditDto city)
        {
            if (id != city.Id)
            {
                Log.Information("(Edit) City was not found");
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var finalCity = Mapper.Map<City>(city);
                    _context.Update(finalCity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                Log.Information("(Delete) City was not found");
                return NotFound();
            }

            var cityEntity = await _context.Cities
                .SingleOrDefaultAsync(m => m.Id == id);
            var city = Mapper.Map<CityDeleteDto>(cityEntity);
            if (city == null)
            {
                Log.Information("(Delete) City was not found");
                return NotFound();
            }

            ViewBag.Title = $@"Delete {city.Name}";

            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var city = await _context.Cities.SingleOrDefaultAsync(m => m.Id == id);
            _context.Cities.Remove(city);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CityExists(int id)
        {
            return _context.Cities.Any(e => e.Id == id);
        }
    }
}

NetCoreMVC/NetCoreMVC/Views/Cities/Create.cshtml
@model NetCoreMVC.Models.CityCreationDto
@{
    Layout = "../_Layout";
}
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Create", "Cities", FormMethod.Post))
        {
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Name)
                    @Html.TextBoxFor(model => model.Name)
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Description)
                    @Html.TextBoxFor(model => model.Description)
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <a href="@Url.Action("Index", "Cities")" class="btn btn-default">Back to Cities</a>
                    <input type="submit" value="Create" class="btn btn-default"/>
                </div>
            </form>
        }        
    </div>
</div>

NetCoreMVC/NetCoreMVC/Views/Cities/Delete.cshtml
@model NetCoreMVC.Models.CityDeleteDto
@{
    Layout = "../_Layout";
}
<hr />
<h4>Are you sure you want to delete this?</h4>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
@using (Html.BeginForm("Delete", "Cities", FormMethod.Post))
{
    <form asp-action="Delete">
        @Html.HiddenFor(model => model.Id)
        <a href="@Url.Action("Index", "Cities")" class="btn btn-default">Back to Cities</a>
        <input type="submit" value="Delete" class="btn btn-default"/> 
    </form>
}
</div>

NetCoreMVC/NetCoreMVC/Views/Cities/Details.cshtml
@model NetCoreMVC.Models.CityDetailsDto
@{
    Layout = "../_Layout";
}
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a href="@Url.Action("Index", "Cities")" class="btn btn-default">Back to Cities</a>
    <a href="@Url.Action("Edit", "Cities")" class="btn btn-default">Edit</a>
</div>

NetCoreMVC/NetCoreMVC/Views/Cities/Edit.cshtml
@model NetCoreMVC.Models.CityEditDto
@{
    Layout = "../_Layout";
}
<hr />
<div class="row">
    <div class="col-md-4">
    @using (Html.BeginForm("Edit", "Cities", FormMethod.Post))
    {
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name)
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description)
                @Html.TextBoxFor(model => model.Description)
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="@Url.Action("Index", "Cities")" class="btn btn-default">Back to Cities</a>
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </form>
    }
    </div>
</div>

NetCoreMVC/NetCoreMVC/Views/Cities/Index.cshtml
@model IEnumerable<NetCoreMVC.Models.CityDto>
@{
    Layout = "../_Layout";
}

<div style="float: right;">
    <a href="@Url.Action("Create", "Cities")" class="btn btn-default">Add City <i class="fas fa-plus"></i></a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <div style="float: right;">
                    <a href="@Url.Action("Edit", "Cities", new {item.Id})"><i class="fas fa-edit fa-lg"></i></a>
                    <a href="@Url.Action("Details", "Cities", new {item.Id})"><i class="fas fa-book fa-lg"></i></a>
                    <a href="@Url.Action("Delete", "Cities", new {item.Id})"><i class="far fa-trash-alt fa-lg"></i></a>
                    
                </div>
            </td>
        </tr>
        }
    </tbody>
</table>